name: github pages

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  deploy-to-github-pages:
  # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v2
    # Setup .NET 7
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.0.3
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
        dotnet-version: 7.x
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools
    - name: Publish .NET Core Project
      run: dotnet publish blazor-wasm.csproj -c:Release -p:GHPages=true -o dist/Web --nologo
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        # This option defaults to the repository scoped GitHub Token.  However if you need more permissions for things such as deploying to another repository, you can add a Personal Access Token (PAT) here.  This should be stored in the `secrets / with` menu **as a secret**.
        # We recommend using a service account with the least permissions necessary and when generating a new PAT that you select the least permission scopes required.
        # [Learn more about creating and using encrypted secrets here.](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
        # token: ${{ github.token }}
        branch: gh-pages
        # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
        folder: dist/Web/wwwroot
